- id: everyone_has_left
  alias: Everyone has left
  trigger:
  - entity_id: group.inhabitants
    platform: state
    to: not_home
  action:
  - data: {}
    service: light.turn_off
  - data:
      entity_id: media_player.living_room
    service: media_player.media_pause
- alias: TV On
  id: tv_on
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'off'
  action:
  - service: media_player.select_source
    data:
      entity_id: media_player.living_room
      source: "Optisk k\xE4lla"
- alias: TV On Sunset
  id: tv_on_sunset
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'off'
  condition:
  - condition: sun
    after: sunset
    after_offset: '-1:00:00'
  action:
  - service: light.hue_activate_scene
    data:
      group_name: Living room
      scene_name: Dimmed
- alias: TV Off Sunset
  id: tv_off_sunset
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'off'
  condition:
    condition: and
    conditions:
    - condition: sun
      after: sunset
      after_offset: '-1:00:00'
    - condition: time
      after: '12:00:00'
      before: 02:00:00
  action:
  - service: light.hue_activate_scene
    data:
      group_name: Living room
      scene_name: Bright
- alias: Sun set
  id: sun_set
  trigger:
  - platform: sun
    event: sunset
    offset: -01:00:00
  condition:
    condition: state
    entity_id: group.inhabitants
    state: home
  action:
  - service: light.hue_activate_scene
    data:
      group_name: Living room
      scene_name: Bright
  - service: light.turn_on
    data:
      entity_id: light.arbetsrum_taklampa_dimmer_level
      brightness: 255
- alias: Coming home
  id: coming_home
  trigger:
    platform: state
    entity_id: group.inhabitants
    to: home
  condition:
    condition: sun
    after: sunset
    after_offset: '-1:00:00'
  action:
    service: light.hue_activate_scene
    data:
      group_name: Living room
      scene_name: Bright
- alias: Weekday dim
  id: weekday_dim
  trigger:
    platform: time
    at: '23:30:00'
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  - condition: state
    entity_id: group.inhabitants
    state: home
  - condition: sun
    after: sunset
    after_offset: '-1:00:00'
  action:
  - service: light.turn_on
    data:
      profile: dimmed
      entity_id: light.living_room
      transition: 60
  - service: light.turn_on
    data:
      entity_id: light.arbetsrum_taklampa_dimmer_level
      brightness: 127
  - service: cover.close_cover
    data:
      entity_id: cover.sovrum_gardin_level
- alias: Weekday night
  id: weekday_night
  trigger:
    platform: time
    at: 00:30:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_off
    data:
      transition: 10
  - service: media_player.media_pause
    data:
      entity_id: media_player.living_room
- alias: Weekday morning Off
  id: weekday_morning_off
  trigger:
  - platform: sun
    event: sunrise
    offset: +01:00:00
  condition:
  - condition: state
    entity_id: group.inhabitants
    state: home
  action:
  - service: light.turn_off
    data:
      transition: 600
- alias: Weekday morning On
  id: weekday_morning_on
  trigger:
    platform: time
    at: 07:30:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: sun
    before: sunrise
  - condition: state
    entity_id: group.inhabitants
    state: home
  action:
    service: light.turn_on
    data:
      profile: bright
      entity_id: light.living_room
      transition: 60
- alias: Alarm clock
  id: alarm_clock
  trigger:
  - entity_id: sensor.the_alarm_clock
    platform: state
  condition:
  - above: '0'
    condition: numeric_state
    entity_id: sensor.the_alarm_clock
  action:
  - data_template:
      entity_id: light.living_room
      profile: bright
      transition: '{{ float(states.sensor.the_alarm_clock.state)*60 }}'
    service: light.turn_on
- alias: Wake up
  id: '1509303589195'
  trigger:
  - at: '7:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: group.inhabitants
    state: home
  action:
  - data:
      brightness: '0'
      entity_id: light.bedroom
      kelvin: '2000'
    service: light.turn_on
  - wait_template:
      "{{ states.light.bedroom.state == 'on'}}"
  - data:
      brightness: '255'
      entity_id: light.bedroom
      kelvin: '2000'
      transition: 10
    service: light.turn_on
  - service: cover.open_cover
    data:
      entity_id: cover.sovrum_gardin_level
- alias: Door Opens
  id: door_opens
  trigger:
  - platform: state
    entity_id: binary_sensor.ytterdorr_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.inhabitants
      state: not_home
    - condition: state
      entity_id: group.all_lights
      state: 'off'
    - condition: or
      conditions:
      - condition: sun
        after: sunset
        after_offset: '-1:00:00'
      - condition: sun
        before: sunrise
        before_offset: '1:00:00'
  action:
  - data: {}
    service: light.turn_on
- alias: "Balkong ljusslinga On"
  id: balkong_ljusslinga
  trigger:
  - platform: sun
    event: sunset
    offset: -01:00:00
  action:
    service: light.turn_on
    entity_id: light.balkong_light
- alias: "Balkong ljusslinga Off"
  id: balkong_ljusslinga
  trigger:
  - platform: sun
    event: sunrise
    offset: 01:00:00
  action:
    service: light.turn_off
    entity_id: light.balkong_light
- alias: Door Opens Notification
  id: door_opens
  trigger:
  - platform: state
    entity_id: binary_sensor.ytterdorr_sensor
    to: 'on'
  condition:
  - condition: state
    entity_id: group.inhabitants
    state: not_home
  action:
  - service: notify.notify
    data:
      message: "Door opened at home."
      
    
        
    
    
      
