- id: everyone_has_left
  alias: Everyone has left
  trigger:
  - entity_id: group.inhabitants
    from: 'on'
    platform: state
  action:
  - data: {}
    service: light.turn_off
  - data:
      entity_id: media_player.living_room
    service: media_player.media_pause
- id: tv_on
  alias: TV On
  trigger:
  - entity_id: media_player.living_room_tv
    platform: state
    to: playing
  action:
  - data:
      entity_id: media_player.living_room
      source: Optisk källa
    service: media_player.select_source
- id: tv_on_sunset
  alias: TV On Sunset
  trigger:
  - entity_id: media_player.living_room_tv
    platform: state
    to: playing
  condition:
  - after: sunset
    after_offset: '-1:00:00'
    condition: sun
  action:
  - data:
      group_name: Living room
      scene_name: Dimmed
    service: hue.hue_activate_scene
- id: tv_off_sunset
  alias: TV Off Sunset
  trigger:
  - entity_id: media_player.living_room_tv
    from: playing
    platform: state
  condition:
  - after: sunset
    after_offset: '-1:00:00'
    condition: sun
  - after: '12:00:00'
    before: 02:00:00
    condition: time
  action:
  - data:
      group_name: Living room
      scene_name: Bright
    service: hue.hue_activate_scene
- alias: Sun set
  id: sun_set
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  condition:
    condition: state
    entity_id: group.inhabitants
    state: 'on'
  action:
  - service: script.light_up_apartment
  - service: light.turn_on
    entity_id: light.balkong_light
- alias: Sun Rise
  id: sun_rise
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 3.5
  action:
  - service: light.turn_off
    entity_id: light.balkong_light
- alias: Weekday dim
  id: weekday_dim
  trigger:
    platform: time
    at: '23:30:00'
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  - condition: state
    entity_id: group.inhabitants
    state: 'on'
  action:
  - service: script.dim_apartment
  - service: cover.close_cover
    data:
      entity_id: cover.sovrum_gardin_level
- alias: Weekday night
  id: weekday_night
  trigger:
    platform: time
    at: 00:30:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_off
    data:
      transition: 10
  - service: media_player.media_pause
    data:
      entity_id: media_player.living_room
- alias: Weekday morning Off
  id: weekday_morning_off
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 3.5
  condition:
  - condition: state
    entity_id: group.inhabitants
    state: 'on'
  action:
  - service: light.turn_off
- id: wake_up
  alias: Wake up
  trigger:
  - at: '7:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: group.inhabitants
    state: 'on'
  action:
  - data:
      entity_id: cover.sovrum_gardin_level
    service: cover.open_cover
  - delay:
      minutes: 5
  - data:
      brightness: 100
      entity_id: light.sovrum_dimmer_level
    service: light.turn_on
  - delay:
      minutes: 5
  - data:
      entity_id:
      - light.sovrum_dimmer_level
      - light.hall_dimmer_level
      - light.koksbank_dimmer_level
      - light.living_room
      profile: bright
    service: light.turn_on
- alias: Door Opens
  id: door_opens
  trigger:
  - platform: state
    entity_id: binary_sensor.ytterdorr_sensor
    to: 'on'
  condition:
  - condition: state
    entity_id: group.inhabitants
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: group.alla_lampor
    state: 'off'
  - condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  action:
  - service: script.light_up_apartment
- alias: We are home
  id: coming_home
  trigger:
  - platform: state
    entity_id: group.inhabitants
    to: 'on'
  condition:
  - condition: state
    entity_id: group.alla_lampor
    state: 'off'
  - condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  action:
  - service: script.light_up_apartment
- id: going_to_bed
  alias: Going To Bed
  trigger:
  - entity_id: binary_sensor.everyone_in_bed
    platform: state
    to: 'on'
  condition:
  - after: '21:00'
    before: '6:00'
    condition: time
  action:
  - service: cover.close_cover
  - data: {}
    service: script.good_night
- id: night_light
  alias: Night light
  trigger:
  - entity_id: binary_sensor.everyone_in_bed
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: 0:30
    before: '6:00'
    condition: time
  - condition: state
    entity_id: light.hallway
    state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.hallway
      profile: night
- id: '1540132430948'
  alias: Daily z-wave healing
  trigger:
  - at: '12:00'
    platform: time
  condition: []
  action:
  - service: zwave.heal_network
