- id: everyone_has_left
  alias: Everyone has left
  trigger:
  - entity_id: group.inhabitants
    platform: state
    to: not_home
  action:
  - data: {}
    service: light.turn_off
  - data:
      entity_id: media_player.living_room
    service: media_player.media_pause
- alias: TV On
  id: tv_on
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'off'
  action:
  - service: media_player.select_source
    data:
      entity_id: media_player.living_room
      source: Optisk källa
- alias: TV On Sunset
  id: tv_on_sunset
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'off'
  condition:
  - condition: sun
    after: sunset
    after_offset: '-1:00:00'
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: Living room
      scene_name: Dimmed
- alias: TV Off Sunset
  id: tv_off_sunset
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'off'
  condition:
    condition: and
    conditions:
    - condition: sun
      after: sunset
      after_offset: '-1:00:00'
    - condition: time
      after: '12:00:00'
      before: 02:00:00
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: Living room
      scene_name: Bright
- alias: Sun set
  id: sun_set
  trigger:
  - platform: sun
    event: sunset
    offset: -01:00:00
  condition:
    condition: state
    entity_id: group.inhabitants
    state: home
  action:
  - service: script.light_up_apartment
- alias: Weekday dim
  id: weekday_dim
  trigger:
    platform: time
    at: '23:30:00'
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  - condition: state
    entity_id: group.inhabitants
    state: home
  - condition: sun
    after: sunset
    after_offset: '-1:00:00'
  action:
  - service: script.dim_apartment
  - service: cover.close_cover
    data:
      entity_id: cover.sovrum_gardin_level
- alias: Weekday night
  id: weekday_night
  trigger:
    platform: time
    at: 00:30:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_off
    data:
      transition: 10
  - service: media_player.media_pause
    data:
      entity_id: media_player.living_room
- alias: Weekday morning Off
  id: weekday_morning_off
  trigger:
  - platform: sun
    event: sunrise
    offset: +01:00:00
  condition:
  - condition: state
    entity_id: group.inhabitants
    state: home
  action:
  - service: light.turn_off
- alias: Wake up
  id: wake_up
  trigger:
  - at: '7:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: group.inhabitants
    state: home
  action:
  - service: cover.open_cover
    data:
      entity_id: cover.sovrum_gardin_level
  - delay:
      minutes: 5
  - service: light.turn_on
    data:
      entity_id: light.sovrum_dimmer_level
      brightness: 100
  - delay:
      minutes: 5
  - service: light.turn_on
    data:
      entity_id:
      - light.sovrum_dimmer_level
      - light.hall_dimmer_level
      - light.koksbank_dimmer_level
      - light.living_room
      profile: bright
- alias: Door Opens
  id: door_opens
  trigger:
  - platform: state
    entity_id: binary_sensor.ytterdorr_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.inhabitants
      state: not_home
      for:
        minutes: 10
    - condition: state
      entity_id: group.alla_lampor
      state: 'off'
    - condition: or
      conditions:
      - condition: sun
        after: sunset
        after_offset: '-1:00:00'
      - condition: sun
        before: sunrise
        before_offset: '1:00:00'
  action:
  - service: script.light_up_apartment
    
- alias: We are home
  id: coming_home
  trigger:
  - platform: state
    entity_id: group.inhabitants
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.alla_lampor
      state: 'off'
    - condition: or
      conditions:
      - condition: sun
        after: sunset
        after_offset: '-1:00:00'
      - condition: sun
        before: sunrise
        before_offset: '1:00:00'
  action:
  - service: script.light_up_apartment
    
- alias: Balkong ljusslinga On
  id: balkong_ljusslinga
  trigger:
  - platform: sun
    event: sunset
    offset: -01:00:00
  action:
    service: light.turn_on
    entity_id: light.balkong_light
- alias: Balkong ljusslinga Off
  id: balkong_ljusslinga
  trigger:
  - platform: sun
    event: sunrise
    offset: 01:00:00
  action:
    service: light.turn_off
    entity_id: light.balkong_light
- action:
  - service: cover.close_cover
  - data: {}
    service: script.good_night
  alias: Going To Bed
  condition:
  - after: '21:00'
    before: '6:00'
    condition: time
  id: going_to_bed
  trigger:
  - entity_id: binary_sensor.everyone_in_bed
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: light.hall_dimmer_level
      profile: dimmed
    service: light.turn_on
  alias: Night light
  condition:
  - after: '0:30'
    before: '6:00'
    condition: time
  - condition: state
    entity_id: light.hall_dimmer_level
    state: 'off'
  id: '1525009433643'
  trigger:
  - entity_id: binary_sensor.everyone_in_bed
    from: 'on'
    platform: state
    to: 'off'
